spring:
  application:
    name: service-feign-hystrix #指定服务名称（全部小写）

server:
  port: 8767

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true