#primary
spring:
  primary:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/test1
      username: root
      password: introcks1234
      driver-class-name: com.mysql.jdbc.Driver

#secondary
  secondary:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/test2
      username: root
      password: introcks1234
      driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect