spring:
  application:
    name: service-consumer-ribbon #指定服务名称（全部小写）

server:
  port: 8764

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
  instance:
    prefer-ip-address: true