spring:
  application:
    name: service-ribbon-hystrix #指定服务名称（全部小写）

server:
  port: 8766

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
  instance:
    prefer-ip-address: true