#datasource
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?charset=utf8mb4&serverTimezone=UTC
    username: root
    password: introcks1234
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
  jackson:
    serialization:
      indent-output: true